### ISSUE TITLE
[...]kaitai/struct/struct.rb:314:in `ensure_fixed_contents': wrong number of arguments (given 1, expected 2) (ArgumentError)

### ISSUE THREAD

**Issue by tschoening** [kaitai-io/kaitai_struct_visualizer#11]
I tried the [zip KSY](https://github.com/kaitai-io/kaitai_struct_formats/blob/master/archive/zip.ksy) of your formats repo with some ordinary zip and got the following error:

	C:\Users\tschoening>ksv "Desktop\zip.zip" "Desktop\zip.ksy"
	Compilation OK
	Class loaded OK
	C:/Users/tschoening/.gem/ruby/2.3.0/gems/kaitai-struct-0.5/lib/kaitai/struct/struct.rb:314:in `ensure_fixed_contents': wrong number of arguments (given 1, expected 2) (ArgumentError)
			from C:/Users/tschoening/AppData/Local/Temp/d20161124-10844-nvzwha/zip.rb:167:in `_read'
			from C:/Users/tschoening/AppData/Local/Temp/d20161124-10844-nvzwha/zip.rb:39:in `_read'
			from C:/Users/tschoening/.gem/ruby/2.3.0/gems/kaitai-struct-visualizer-0.5/lib/kaitai/struct/visualizer/visualizer.rb:29:in `initialize'
			from C:/Users/tschoening/.gem/ruby/2.3.0/gems/kaitai-struct-visualizer-0.5/bin/ksv:19:in `new'
			from C:/Users/tschoening/.gem/ruby/2.3.0/gems/kaitai-struct-visualizer-0.5/bin/ksv:19:in `<top (required)>'
			from C:/Users/tschoening/.gem/ruby/2.3.0/bin/ksv:23:in `load'
			from C:/Users/tschoening/.gem/ruby/2.3.0/bin/ksv:23:in `<main>'

I'm pretty sure the Zip itself is valid and I tried different ones as well, all with the same result.

Additionally:

Is there some arg to tell `ksv` to not delete the temporarily compiled classes? If not, interested to add one?

Currently those temp folders seem to be deleted on program exit, which is fine in the default case of course. But in cases like these they might be of value for debugging. My main environment isn't Ruby, so I would need to do `things` to compile the classes again, which in theory are unnecessary because `ksv` did all those things already. I would just need to tell it to not remove the files and at least could have a first look myself.

**Comment by GreyCat** [comment]
> I'm pretty sure the Zip itself is valid and I tried different ones as well, all with the same result.

API of `ensure_fixed_contents` has changed recently. If you use current compiler, then you're expected to keep all runtimes + visualizer up-to-date as well. Please update Ruby runtime as well. If you don't want to deal with building gems yourself, then probably just getting [this file](https://raw.githubusercontent.com/kaitai-io/kaitai_struct_ruby_runtime/master/lib/kaitai/struct/struct.rb) and replacing your `C:/Users/tschoening/.gem/ruby/2.3.0/gems/kaitai-struct-0.5/lib/kaitai/struct/struct.rb` should do the trick.

> Is there some arg to tell ksv to not delete the temporarily compiled classes? If not, interested to add one?

Not yet. Technically, you can always get the exactly same compiled class by running it `ksc -t ruby --debug original.ksy`. Of course, it's easy to implement some command-line option to just leave them be (or even compile them to current or some designated directory, for example, not to temp dir). I'll try to implement one, thanks for the idea :)

**Comment by tschoening** [comment]
Thanks, totally forgot about those dependencies. For now it was easier to provide some older, compatible compiler again. I hope I keep that in mind if I use KSY files with unsupported features and stuff. :-)

**Comment by tschoening** [comment]
Guten Tag Mikhail Yakshin,
am Donnerstag, 24. November 2016 um 15:36 schrieben Sie:

> If you don't want to deal with building gems yourself, then probably
> just getting [this
> file](https://raw.githubusercontent.com/kaitai-io/kaitai_struct_ruby_runtime/master/lib/kaitai/struct/struct.rb)
> and replacing your
> `C:/Users/tschoening/.gem/ruby/2.3.0/gems/kaitai-struct-0.5/lib/kaitai/struct/struct.rb`
> should do the trick.

Just in case anyone else has a similar problem: You don't need the
gems at all. I find it easier to clone the kaitai_struct repo
including all its submodules to some directory and that already
contains the visualizer and the corresponding runtime in a compatible
version. The visualizer already takes exactly that setup into account,
by adding the runtime/ruby-dir into its lib paths, and the only thing
you need to do is calling the visualizer like the ksv.bat
distributed with the gem would do.

Some example, just adopt it to your paths and shell or whatever:

> "%ProgramFiles(x86)%\Ruby23\bin\ruby.exe" "%ProgramFiles(x86)%\kaitai-struct\visualizer\bin\ksv" "%USERPROFILE%\Desktop\data.bin" "collector\FmtsCltRecords.ksy" "oms\*.ksy"

Mit freundlichen Grüßen,

Thorsten Schöning

-- 
Thorsten Schöning       E-Mail: Thorsten.Schoening@AM-SoFT.de
AM-SoFT IT-Systeme      http://www.AM-SoFT.de/

Telefon...........05151-  9468- 55
Fax...............05151-  9468- 88
Mobil..............0178-8 9468- 04

AM-SoFT GmbH IT-Systeme, Brandenburger Str. 7c, 31789 Hameln
AG Hannover HRB 207 694 - Geschäftsführer: Andreas Muchow
