### ISSUE TITLE
unable to run

### ISSUE THREAD

**Issue by evandrix** [kaitai-io/kaitai_struct_visualizer#13]
`$ ksv 1194614.gif gif.ksy`

**error message**
````
/eta: unknown key found, expected: enums, instances, meta, seq, types
Compilation OK
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': no implicit conversion of nil into String (TypeError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/kaitai-struct-visualizer-0.5/lib/kaitai/struct/visualizer/visualizer_main.rb:31:in `block in compile_format'
	from /usr/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
	from /var/lib/gems/2.3.0/gems/kaitai-struct-visualizer-0.5/lib/kaitai/struct/visualizer/visualizer_main.rb:10:in `compile_format'
	from /var/lib/gems/2.3.0/gems/kaitai-struct-visualizer-0.5/lib/kaitai/struct/visualizer/visualizer.rb:18:in `initialize'
	from /var/lib/gems/2.3.0/gems/kaitai-struct-visualizer-0.5/bin/ksv:19:in `new'
	from /var/lib/gems/2.3.0/gems/kaitai-struct-visualizer-0.5/bin/ksv:19:in `<top (required)>'
	from /usr/local/bin/ksv:23:in `load'
	from /usr/local/bin/ksv:23:in `<main>'
````

**Comment by GreyCat** [comment]
Judging from `/eta: unknown key found`, you've got a key named `eta` on the top level of the gif.ksy file, while it should be named `meta`. Copy-paste error?

**Comment by thsieh123** [comment]
Could be that kaitai_struct's commit c27986b404 broke binary compatibility. Wonder how to rebuild kaitai_struct_visualizer?

**Comment by thsieh123** [comment]
ah, sorry, I got it working now.

**Comment by GreyCat** [comment]
@thsieh123 Sorry for late reply %) Indeed, you've encountered incompatibility between 0.5 and upcoming 0.6 API. You need to either user 0.5 everywhere (i.e. both runtime and compiler), or current git (upcoming 0.6) everywhere (i.e. compile the compiler from git + use Ruby runtime from git). As far as I remember, visualizer itself had no major API changes between 0.5 and 0.6, so it's only a matter of ksc vs runtime.

Actually, this case gave a good idea that we probably need to add some sanity checks into generated code, to check the version of API.

**Comment by GreyCat** [comment]
@thsieh123 I've added this as an issue to main KS project: https://github.com/kaitai-io/kaitai_struct/issues/72

**Comment by thsieh123** [comment]
Thanks!
