### ISSUE TITLE
Feature Request: __str__ and __repr__ for python generated classes

### ISSUE THREAD

**Issue by amrnablus** [kaitai-io/kaitai_struct_visualizer#22]
the methods are equivalent to java's toString method, having them generated by kaitai would greatly ease the debugging.

**Comment by GreyCat** [comment]
This actually doesn't have anything to do with kaitai_struct_visualizer project, and in the main repo there's a broader task for it: https://github.com/kaitai-io/kaitai_struct/issues/299

Please continue the discussion there.
