### ISSUE TITLE
Instances do not highlight types as groups of values

### ISSUE THREAD

**Issue by Icekhaos** [kaitai-io/kaitai_struct_visualizer#36]
Types used in seq will display the type, when selected by itself, and when components are highlighted, as a group. That is, it'll highlight the entire type structure, with the particular thing you have selected being highlighted brighter than everything else. Instances do not do this.

Is this a bug, or just a currently NI feature?

Also semi related: selecting the type itself (and not any of the values/arrays contained within) does not highlight the entire type. This also happens with seq stuff.

**Comment by GreyCat** [comment]
Unfortunately, it's not very clear what you're talking about.

> Types used in seq will display the type

What is "display the type"?

> when selected by itself

What is "types used in seq ... when selected by itself"?

> and when components are highlighted,

What are "components"?

> That is, it'll highlight the entire type structure

I have no idea what do you mean by "entire type structure"?

Can I ask you to rephrase what you wanted to say using common terminology, e.g. one used in [KSY schema](https://github.com/kaitai-io/ksy_schema/), [user guide](https://doc.kaitai.io/user_guide.html) or [sources](https://github.com/kaitai-io/kaitai_struct_compiler/tree/master/shared/src/main/scala/io/kaitai/struct/format)?

**Comment by Icekhaos** [comment]
I will just post pictures of what I mean.

Here it is using seq:
![image](https://user-images.githubusercontent.com/4009373/80421020-4aa09d00-88cb-11ea-8fd3-6a05a4429a4a.png)
Here it is using instances:
![image](https://user-images.githubusercontent.com/4009373/80421114-7a4fa500-88cb-11ea-91f5-8b8b6e2b62e1.png)

Yet another minor thing, unrelated to this, is that there is a question mark when instances are used until I expand the type:
![image](https://user-images.githubusercontent.com/4009373/80421147-88052a80-88cb-11ea-9a33-644949438e0d.png)
