### ISSUE TITLE
Suggestion: Configure GitHub RuboCop Action

### ISSUE THREAD

**Issue by iamazeem** [kaitai-io/kaitai_struct_visualizer#38]
Please configure the GitHub RuboCop Action.
Reference: https://github.com/marketplace/actions/github-rubocop-action

PS:
With this change, there will be a need to have a strict guideline for new code to run RuboCop locally first before committing the changes.

Regards!

**Comment by generalmimon** [comment]
Actually, we are running RuboCop in the CI workflow for a while now, see `.github/workflows/build.yml:33-34`:

https://github.com/kaitai-io/kaitai_struct_visualizer/blob/231beb54b77d0161799d5227865f4d6f7fcd56f8/.github/workflows/build.yml#L33-L34

So this issue is resolved.
