### ISSUE TITLE
README: Add installation instructions

### ISSUE THREAD

**Issue by tegob** [kaitai-io/kaitai_struct_visualizer#5]
How to install `ksv`? Please mention it in the README.

Is this how?

``` sh
gem install specific_install
gem specific_install -l https://github.com/kaitai-io/kaitai_struct_visualizer.git
```

**Comment by GreyCat** [comment]
Good idea, I'll try to add it now.

**Comment by GreyCat** [comment]
Here you go: https://github.com/kaitai-io/kaitai_struct_visualizer#downloading-and-installing
Is it clear enough / solves your problem?

**Comment by GreyCat** [comment]
How that means yes. It's been more than a month now, so I'm closing this one.
