### ISSUE TITLE
Make ksdump output only JSON on success

### ISSUE THREAD

**Issue by wader** [kaitai-io/kaitai_struct_visualizer#56]
Hi, i think `ksdump -f json` would be easier to use with jq etc and be more what i would expect if only outputted JSON on stdout. Currently it also outputs some log messages on stdout making the output invalid JSON. Maybe on error it could print logs on stderr?

Reproduction:
```
$ docker run -v "$PWD:/share" -it --entrypoint=ksdump kaitai/ksv -f json /dev/zero some.ksy
Compilation OK
... processing substring_diff.ksy 0
...... loading substring_diff.rb
Classes loaded OK, main class = SubstringDiff
{
  "a": ""
}
```

Workaround i use at the moment is to pipe thru tail `ksdump ... | tail +5 | jq ...`.

If good ide I guess same would apply for XML and YAML output.

I also noticed that there is no trailing new line for the last JSON output line, making it a bit awkward in a shell.

**Comment by wader** [comment]
🎉 

BTW sorry for little progress on the fq kaitai front. Ended up being involved in getting jq maintained again after 5 years without any release and hopefully jq 1.7 will be out soon!

**Comment by generalmimon** [comment]
> Ended up being involved in getting jq maintained again after 5 years without any release and hopefully jq 1.7 will be out soon!

The pre-release version actually popped up in my feed recently - that's super exciting! jq is amazing for all sorts of JSON manipulation and it's easy and quick to use, but yeah, I wasn't sure whether there would be a successor of jq 1.6 after this time 😉
