### ISSUE TITLE
Why is Rake declared as a development dependency?

### ISSUE THREAD

**Issue by generalmimon** [kaitai-io/kaitai_struct_visualizer#57]
Cc @GreyCat

See `.gemspec`:

https://github.com/kaitai-io/kaitai_struct_visualizer/blob/4e273ada5131e0530b39793a73fff7af753395ab/kaitai-struct-visualizer.gemspec#L34

When I just run `rake` in the console, it fails because there is no "rakefile":

```console
$ rake
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)

(See full trace by running task with --trace)
```

I'm not familiar with Rake at all, I just have a hunch that it's like writing `Makefile`s in Ruby (and I saw a few gems that were using a `Rakefile` to build native extensions, for example). But I think we don't use Rake in any way here?

**Comment by GreyCat** [comment]
To be honest, I'm not sure. My best guess is that I've copy-pasted that from some ancient tutorial about building gemspecs, and it stuck around. In absence of Rakefiles, and really no usage of it whatsoever, I assume it should be ok to remove.

**Comment by GreyCat** [comment]
Removed rake, also added GH action to run builds / tests / rubocop. Works fine so far (except for rubocop warnings).
