### ISSUE TITLE
How to close ksv on Windows?

### ISSUE THREAD

**Issue by tschoening** [kaitai-io/kaitai_struct_visualizer#7]
This might sound stupid, but how do I close `ksv`? I tried STRG+C, +D, +Z an it's always just repainting. The only way to close it I found was the "X" of the shell Window. The problem with this is that one looses the commandline to open `ksv` and it's a bit annoying to always need to retype paths.

**Comment by GreyCat** [comment]
Um, it's the same on all platforms. `q` does the trick - it comes from UNIX background and is pretty standard there - `more`, `less`, etc.

I agree that we should probably add something like Escape on Windows platform to act as quit button as well, plus we should add some online help shown by F1 or `?` or something like that.

**Comment by GreyCat** [comment]
By the way, it's really kind of funny as why it never surfaced before. In fact, I've just held a fairly large workshop (~100 people) on Kaitai Struct. I was showing them `ksv` as well, and I know that at least one third of them used Windows, but not a single soul asked for that — and I fully admit that pressing `q` must be pretty foreign for Windows users ;)

**Comment by tschoening** [comment]
Didn't think of `q`, even I use `vi` and such pretty often. :-) Escape or STRG+C would be more intuitive, though. Besides heavy work for some online help, how about simply adding an additional line at the bottom of your already present status line hinting at `q`? At least I would have noticed...
