### ISSUE TITLE
key pressing error

### ISSUE THREAD

**Issue by audiserg** [kaitai-io/kaitai_struct_visualizer#9]
ubuntu 12.04
```
 /usr/lib/ruby/gems/1.9.1/gems/kaitai-struct-visualizer-0.5/lib/kaitai/console_ansi.rb:94:in `read_char': undefined method `cooked!' for #<IO:<STDIN>> (NoMethodError)
```

**Comment by GreyCat** [comment]
According to [APIDock](http://apidock.com/ruby/IO/cooked!), Ruby 1.9 should have `IO#cooked` support. However, probably it was added only at 1_9_3_392, and, judging by "1.9.1" in your path, you have 1.9.1. If you can upgrade, why don't you just upgrade for the last stable Ruby, i.e. 2.3.3?

P.S. What language do you speak? May be we can speak in your language?

**Comment by audiserg** [comment]
I speak Russian. Для Ubuntu 12-04 нет обновления 2.3.3. Версия 1.9.3 использует библиотеки 1.9.1, насколько я понял

**Comment by GreyCat** [comment]
Есть какая-то принципиальная необходимость использовать именно 12.04? Система весьма древняя - чтобы поддерживать такое, по хорошему, надо все действительно обвешивать тестами и тщательно проверять. Учитывая, что этот консольный визуализатор - проект весьма побочный, на него сейчас тратить время не очень хочется.

`ruby --version` у вас сейчас что выводит?

Как альтернативу - можете рассмотреть возможность использовать [WebIDE](https://kt.pe/kaitai_struct_webide/)?

**Comment by audiserg** [comment]
Это замкнутый круг, chrome 32 bit тоже не поддерживается. Переставлять и обновлять систему не хочется т.к. много чего стоит с такими же костылями. просто так потом не поднять. Визуализатор имеет версию под windows?  может я смогу в wine его запустить?

**Comment by GreyCat** [comment]
Визуализатор по идее запускается под Windows. Под Wine, насколько я знаю, его никто не пробовал. Можно попробовать в виртуальной машине (через vagrant, например, это вообще легко должно быть сделать) поднять более современную систему. Ну или просто взять пакеты Ruby из современных Ubuntu/Debian - по идее там зависимостей должно быть мало, частично обновить...

**Comment by audiserg** [comment]
под windows есть exe файл или он запускается в интерпретаторе?

**Comment by GreyCat** [comment]
Под Windows `gem install` генерирует bat-файл, который в свою очередь будет запускать ruby.exe.

**Comment by GreyCat** [comment]
Судя по отсутствию комментариев - проблема или решена, или так или иначе себя исчерпала.

В любом случае, пока планов поддерживать Ruby 1.8 или 1.9.1 нет - это приличный объем работы, поэтому, боюсь, что по конкретному этому вопросу - wontfix.
